### ISSUE TITLE
Request for disabling invert for PDF export 

### ISSUE THREAD

**Issue by Sandwich1699975** [ozntel/oz-image-in-editor-obsidian#107]
As I use dark mode for obsidian, and light mode for PDF; I would like to be able to disable invert when exporting to PDF. So my images are not black on white paper. Example:

```css
/* PDF Styles */

@media print {
    .theme-dark img[alt$='#invert'] {
        /* Fix invert for images */
        filter: invert(0) hue-rotate(360deg);
    }
}
```

This worked for me for a bit, but not any more.
A settings toggle, or automatic disable would be amazing.

Thank you
