### ISSUE TITLE
Alt text #small is not effective in preview mode

### ISSUE THREAD

**Issue by Yaozhuwa** [ozntel/oz-image-in-editor-obsidian#17]
Alt text #small #x-small is not effective in preview mode.
Although the new feature`![100x100](image.png)` can effect both edit and preview mode, I prefer to use #small for it's elegance.

**Comment by ozntel** [comment]
Hi @Yaozhuwa I specifically added CSS including only the styling in Editor. I

n case you want `#small` option to work in preview you can include the following CSS rules:

```css
img[alt$='#small'] {
  max-width: 75% !important;
  min-width: 200pt !important;
}

img[alt$='#x-small'] {
  max-width: 50% !important;
  min-width: 100pt !important;
}

img[alt$='#xx-small'] {
  max-width: 25% !important;
  min-width: 50pt !important;
}
```

or another option is to use `100x100` format (`Width x Height`). I just included support for this format today. Instead of `#x-small`, you can use either single width value or width & height:

`![[myimage.png|500x500]]`
`![[myimage.png|500]]`

Since Obsidian has native support for this format, it should work in both Preview and Editor the same way.

Please make sure that you update to the latest version.

Hope this helps.
