### ISSUE TITLE
inverted color mode

### ISSUE THREAD

**Issue by trungng2006** [ozntel/oz-image-in-editor-obsidian#32]
Currently, minimal theme have inverted mode for picture by adding #invert at the end.
Ex: ![[Picture1.bmp#invert]]
Could you please kindly add this option for the plugin?

**Comment by ozntel** [comment]
What you can do is to add `#invert` as an `alt-text` rather than directly to the `src` attribute as below:

```
![[picture.bmp|#invert]]
```

and add the following CSS snippet to your style:

```css
.theme-dark img[alt$="#invert"], .theme-dark div.oz-image-widget > img[alt$="#invert"] {
	filter: invert(1) hue-rotate(180deg);
	mix-blend-mode: screen;
}
```

And it will work in all themes within preview and edit modes.
