### ISSUE TITLE
Rendering transclusions

### ISSUE THREAD

**Issue by DutchPete** [ozntel/oz-image-in-editor-obsidian#55]
Many thanks for incorporating this feature. It works very well for me ! Another step towards the WYSIWYG experience.

How can I hide the vertical line on the left next to the transclusion?

**Comment by ozntel** [comment]
You can overwrite border in your custom snippet:

```css
.oz-transclusion-widget {
	padding: 3px 3px 3px 15px;
	border-left: 2px solid var(--text-muted);
}
```
